services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  localai:
    image: localai/localai:v2.25.0-ffmpeg-core
    ports:
      - 8081:8080
    environment:
      - LOG_LEVEL=INFO
      - MODELS_PATH=/models
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DISABLE_REQUIRE=1 
      # - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ./models:/models:rw
    # runtime: nvidia
    depends_on:
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/models"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
